import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from ".Components/Navbar";
// import Components from "../components/navbar.js"

export default function Home() {
  return (
    <div className={styles.container}>
        {/* <header>
            <h3>Logo</h3>
            <nav>
                <a href="/#">Events</a>
                <a href="/#">Contact</a>
                <a href="/#">Filter</a>
            </nav>
        </header> */}
      <Head>
        <title>SF Funcheap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>SF Funcheap</h1>

        {/* <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p> */}

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Hella Secret SF Comedy Show &rarr;</h2>
            <p>Like</p>
            <p>View Details</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Halloween Party &rarr;</h2>
            <p>Like</p>
            <p>View Details</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Harvest Festival &rarr;</h2>
            <p>Like</p>
            <p>View Details</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Pumpkin Patch &rarr;</h2>
            <p>Like</p>
            <p>View Details</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
